import './i18n-ui.js';
import { post } from './api.js';
import { FALLBACK_QUESTIONS } from './config.js';
import { byId, safeText } from './dom.js';
import { getLocale, initI18n, t } from './i18n.js';
import { renderReport, revealReport } from './report.js';
import { resetState, state } from './state.js';
import { analysisDurationMs, markAnalysisStarted, track } from './tracking.js';
import { setProgress, showView } from './ui.js';
import { completeFreeAnalysis, guardFreeStart, initFreePlan, resetFreeView } from './free-stable.js';
import { initWorkspace, saveGeneratedProject, startNewWorkspaceProject } from './workspace.js';

let loadingTimer;
function startLoading(){let index=0;const update=()=>{const messages=t('runtime.loading');byId('loading-copy').textContent=messages[index%messages.length];};update();clearInterval(loadingTimer);loadingTimer=setInterval(()=>{index+=1;update();},900);}
function stopLoading(){clearInterval(loadingTimer);}
function translatedFallbackQuestions(){return getLocale()==='en'?[{question:'Who is the first specific customer for this idea?',reason:'Target customer'},{question:'What urgent problem are they solving today and with which alternative?',reason:'Problem evidence'},{question:'What real evidence suggests they would pay?',reason:'Willingness to pay'},{question:'How would you reach the first ten customers?',reason:'Distribution'},{question:'What is the smallest test you can run in seven days?',reason:'Validation'}]:FALLBACK_QUESTIONS;}
function renderQuestion(){showView('question-view');const total=state.questions.length;const question=state.questions[state.index]||{};byId('question-title').textContent=question.question||question.text||t('runtime.fallbackQuestion');byId('question-reason').textContent=question.reason||question.dimension||t('runtime.adapted');byId('answer').value='';setProgress(15+(state.index/Math.max(1,total))*55,t('runtime.question',{current:state.index+1,total}));track('question_viewed',{step:state.index+1,total,questionDimension:question.dimension||'unknown'});byId('answer').focus();}
function renderBlocked(result){showView('report-view');setProgress(100,t('runtime.stopped'));renderReport({score:0,verdict:t('runtime.blockedVerdict'),summary:safeText(result.reason)||t('runtime.blockedSummary'),strengths:[],risks:[t('runtime.blockedRisk')],assumptions:[],doNotBuildYet:[t('runtime.blockedDont')],experiment:{name:t('runtime.safeStep'),steps:[t('runtime.safeAction')]}});track('screening_blocked');}
async function startAnalysis(){if(!guardFreeStart())return;const idea=safeText(byId('idea').value);byId('start-error').textContent='';if(idea.length<12){byId('start-error').textContent=t('runtime.detailError');return;}state.idea=idea;markAnalysisStarted();byId('start-button').disabled=true;showView('loading-view');setProgress(12,t('runtime.analyzing'));startLoading();track('validator_started');try{const result=await post('/api/analyze',{stage:'screen',idea,language:getLocale(),locale:getLocale()});if(result.status==='blocked'||result.classification==='prohibited'){stopLoading();renderBlocked(result);return;}state.questions=Array.isArray(result.questions)&&result.questions.length?result.questions:translatedFallbackQuestions();state.answers=[];state.index=0;state.maturity=result.maturity||'unknown';state.profile=result.profile||'unknown';state.mode=result.mode||'unknown';stopLoading();renderQuestion();}catch(error){stopLoading();showView('start-view');setProgress(0,t('runtime.stepOne'));byId('start-error').textContent=error.message;track('analysis_error',{errorCode:'screen_request_failed'});}finally{byId('start-button').disabled=false;}}
async function submitAnswer(){const value=safeText(byId('answer').value);if(value.length<3){byId('answer').focus();return;}const question=state.questions[state.index]||{};track('question_answered',{step:state.index+1,total:state.questions.length,questionDimension:question.dimension||'unknown'});state.answers.push({question:byId('question-title').textContent,answer:value});state.index+=1;if(state.index<state.questions.length){renderQuestion();return;}showView('loading-view');setProgress(78,t('runtime.preparing'));startLoading();track('questionnaire_completed',{total:state.questions.length});try{const report=await post('/api/analyze',{stage:'report',idea:state.idea,answers:state.answers,language:getLocale(),locale:getLocale()});if(report.status==='blocked'||report.classification==='prohibited'){stopLoading();renderBlocked(report);return;}state.report=report;state.maturity=report.maturity||state.maturity||'unknown';state.profile=report.profile||state.profile||'unknown';state.mode=report.mode||state.mode||'unknown';stopLoading();await revealReport(report);completeFreeAnalysis();saveGeneratedProject({idea:state.idea,answers:state.answers,report:state.report,maturity:state.maturity,profile:state.profile,mode:state.mode});track('report_generated',{score:report.score,verdict:report.verdict,maturity:state.maturity,profile:state.profile,mode:state.mode,durationMs:analysisDurationMs()});}catch(error){stopLoading();showView('question-view');state.index=Math.max(0,state.questions.length-1);byId('question-title').textContent=t('runtime.reportError');byId('question-reason').textContent=error.message;byId('answer').classList.add('hidden');byId('answer-button').textContent=t('runtime.retry');track('analysis_error',{errorCode:'report_request_failed'});}}
function resetAnalysis(){startNewWorkspaceProject();resetState();byId('idea').value='';byId('answer').classList.remove('hidden');byId('answer-button').textContent=t('validator.continue');showView('start-view');setProgress(0,t('runtime.stepOne'));resetFreeView();byId('idea').focus();track('restart_clicked');}
async function shareReport(){const report=state.report||{};const text=`Atlas — ${report.verdict||t('runtime.validationReport')}\n${t('runtime.score')}: ${report.score??'—'}/100\n${report.executiveSummary||report.summary||''}`;try{if(navigator.share){await navigator.share({title:`Atlas — ${t('runtime.validationReport')}`,text,url:location.href});}else{await navigator.clipboard.writeText(`${text}\n${location.href}`);byId('share-button').textContent=t('runtime.copied');setTimeout(()=>{byId('share-button').textContent=t('validator.share');},1500);}track('report_shared');}catch{}}
async function downloadReport(){const button=byId('pdf-button');if(!state.report||button.disabled)return;const original=button.textContent;button.disabled=true;button.textContent=getLocale()==='en'?'Generating PDF...':'Generando PDF...';try{const response=await fetch('/api/report-pdf',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({idea:state.idea,report:state.report,locale:getLocale()})});if(!response.ok){let message='Atlas could not generate the PDF.';try{const data=await response.json();message=data.error||message;}catch{}throw new Error(message);}const blob=await response.blob();const disposition=response.headers.get('content-disposition')||'';const match=disposition.match(/filename="([^"]+)"/i);const filename=match?.[1]||(getLocale()==='en'?'atlas-validation-report.pdf':'atlas-informe-validacion.pdf');const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);track('pdf_downloaded',{generator:'server_pdf_v1'});}catch(error){console.error('atlas_pdf_failed',error);alert(getLocale()==='en'?'The PDF could not be generated. Please try again.':'No se pudo generar el PDF. Inténtalo de nuevo.');track('analysis_error',{errorCode:'pdf_generation_failed'});}finally{button.disabled=false;button.textContent=original;}}
function bindEvents(){byId('start-button').addEventListener('click',startAnalysis);byId('answer-button').addEventListener('click',submitAnswer);byId('restart-button').addEventListener('click',resetAnalysis);byId('new-analysis-button').addEventListener('click',resetAnalysis);byId('share-button').addEventListener('click',shareReport);byId('pdf-button').addEventListener('click',downloadReport);byId('idea').addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter')startAnalysis();});byId('answer').addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter')submitAnswer();});window.addEventListener('atlas:locale',()=>{track('locale_changed');if(!state.idea)setProgress(0,t('runtime.stepOne'));if(state.report)renderReport(state.report);});}
initI18n();initFreePlan();initWorkspace();bindEvents();setProgress(0,t('runtime.stepOne'));resetFreeView();track('landing_view');
