import { getLocale } from './i18n.js';

const STORAGE_KEY='atlas-pro-workspace-v1';
let activeProjectId='';
let running=false;
let controller=null;
const conversations=new Map();

const copy=()=>getLocale()==='en'?{
button:'Copilot',title:'Atlas Copilot',subtitle:'Ask questions using the full context of this project.',close:'Close',placeholder:'Ask about risks, evidence or the next experiment…',send:'Send',thinking:'Thinking…',empty:'Ask Atlas what you should validate next.',failed:'Atlas Copilot could not respond.',suggestions:['What is my biggest risk now?','What should I validate this week?','What evidence am I missing?','Why did my score change?','What should I avoid building?','Draft my next experiment.'],actions:'Suggested next actions'
}:{
button:'Copiloto',title:'Copiloto Atlas',subtitle:'Pregunta usando todo el contexto de este proyecto.',close:'Cerrar',placeholder:'Pregunta por riesgos, evidencias o el próximo experimento…',send:'Enviar',thinking:'Pensando…',empty:'Pregunta a Atlas qué deberías validar ahora.',failed:'El Copiloto Atlas no pudo responder.',suggestions:['¿Cuál es mi mayor riesgo ahora?','¿Qué debería validar esta semana?','¿Qué evidencia me falta?','¿Por qué cambió mi puntuación?','¿Qué no debería construir?','Redáctame el siguiente experimento.'],actions:'Siguientes acciones sugeridas'
};

function readProjects(){try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(value)?value:[];}catch{return[];}}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
function history(projectId){if(!conversations.has(projectId))conversations.set(projectId,[]);return conversations.get(projectId);}
function compactProject(project){return{name:project.name||'',idea:project.idea||'',answers:Array.isArray(project.answers)?project.answers.slice(0,12):[],report:project.report||{},versions:Array.isArray(project.versions)?project.versions.slice(-5):[],evidence:Array.isArray(project.evidence)?project.evidence.slice(-20):[],timeline:Array.isArray(project.timeline)?project.timeline.slice(-20):[],maturity:project.maturity,profile:project.profile,mode:project.mode};}
function ensureStyles(){if(document.getElementById('atlas-copilot-styles'))return;const style=document.createElement('style');style.id='atlas-copilot-styles';style.textContent=`.copilot-modal{position:fixed;inset:0;z-index:1300;display:grid;place-items:center;padding:16px;background:rgba(2,7,15,.82);backdrop-filter:blur(14px)}.copilot-modal.hidden{display:none}.copilot-panel{width:min(860px,100%);height:min(760px,92vh);display:grid;grid-template-rows:auto 1fr auto;border:1px solid var(--line);border-radius:24px;background:linear-gradient(150deg,#0f1d33,#071321);box-shadow:0 40px 120px rgba(0,0,0,.62);overflow:hidden}.copilot-head{display:flex;justify-content:space-between;gap:16px;padding:20px;border-bottom:1px solid var(--line)}.copilot-head h2{margin:4px 0 5px}.copilot-head p{margin:0;color:var(--muted)}.copilot-close{border:1px solid var(--line);border-radius:12px;background:#081523;color:var(--text);padding:10px 13px;cursor:pointer}.copilot-body{overflow:auto;padding:18px;display:grid;align-content:start;gap:12px}.copilot-empty{padding:24px;border:1px dashed var(--line);border-radius:16px;text-align:center;color:var(--muted)}.copilot-suggestions{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;margin-top:14px}.copilot-suggestions button{border:1px solid rgba(91,201,255,.25);border-radius:999px;background:rgba(91,201,255,.07);color:var(--text);padding:8px 11px;cursor:pointer}.copilot-message{max-width:84%;padding:13px 15px;border-radius:16px;line-height:1.55;white-space:pre-wrap}.copilot-message[data-role="user"]{justify-self:end;background:rgba(91,201,255,.14);border:1px solid rgba(91,201,255,.28)}.copilot-message[data-role="assistant"]{justify-self:start;background:#081523;border:1px solid var(--line)}.copilot-message ul{margin:10px 0 0;padding-left:20px}.copilot-message small{display:block;color:var(--blue);margin-bottom:5px;font-weight:800;text-transform:uppercase;letter-spacing:.06em}.copilot-form{display:grid;grid-template-columns:1fr auto;gap:10px;padding:16px;border-top:1px solid var(--line);background:rgba(4,12,22,.88)}.copilot-form textarea{min-height:48px;max-height:130px;resize:vertical;border:1px solid var(--line);border-radius:13px;background:#06111e;color:var(--text);padding:12px;font:inherit}.copilot-form button{border:1px solid rgba(91,201,255,.45);border-radius:13px;background:rgba(91,201,255,.13);color:var(--text);padding:0 18px;font-weight:800;cursor:pointer}.copilot-form button:disabled{opacity:.55;cursor:wait}@media(max-width:700px){.copilot-panel{height:94vh;border-radius:18px}.copilot-head{padding:16px}.copilot-body{padding:14px}.copilot-message{max-width:94%}.copilot-form{grid-template-columns:1fr}.copilot-form button{min-height:44px}}`;document.head.appendChild(style);}
function modal(){let root=document.getElementById('atlas-copilot-modal');if(root)return root;ensureStyles();root=document.createElement('div');root.id='atlas-copilot-modal';root.className='copilot-modal hidden';root.innerHTML='<section class="copilot-panel" role="dialog" aria-modal="true"><header class="copilot-head"><div><p class="eyebrow">ATLAS</p><h2 data-copilot-title></h2><p data-copilot-subtitle></p></div><button class="copilot-close" type="button" data-copilot-close>×</button></header><div class="copilot-body" data-copilot-body></div><form class="copilot-form" data-copilot-form><textarea maxlength="1200" data-copilot-input></textarea><button type="submit" data-copilot-send></button></form></section>';document.body.appendChild(root);root.addEventListener('click',event=>{if(event.target===root||event.target.closest('[data-copilot-close]'))close();});root.querySelector('[data-copilot-form]').addEventListener('submit',event=>{event.preventDefault();send();});root.querySelector('[data-copilot-input]').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();send();}});return root;}
function render(){const c=copy(),root=modal(),body=root.querySelector('[data-copilot-body]');root.querySelector('[data-copilot-title]').textContent=c.title;root.querySelector('[data-copilot-subtitle]').textContent=c.subtitle;root.querySelector('[data-copilot-input]').placeholder=c.placeholder;root.querySelector('[data-copilot-send]').textContent=running?c.thinking:c.send;const items=history(activeProjectId);if(!items.length){body.innerHTML=`<div class="copilot-empty">${escapeHtml(c.empty)}<div class="copilot-suggestions">${c.suggestions.map(item=>`<button type="button" data-copilot-suggestion="${escapeHtml(item)}">${escapeHtml(item)}</button>`).join('')}</div></div>`;body.querySelectorAll('[data-copilot-suggestion]').forEach(button=>button.addEventListener('click',()=>{root.querySelector('[data-copilot-input]').value=button.dataset.copilotSuggestion;send();}));return;}body.innerHTML=items.map(item=>`<article class="copilot-message" data-role="${item.role}">${item.role==='assistant'?'<small>Atlas</small>':''}${escapeHtml(item.content)}${item.actions?.length?`<strong>${escapeHtml(c.actions)}</strong><ul>${item.actions.map(action=>`<li>${escapeHtml(action)}</li>`).join('')}</ul>`:''}</article>`).join('');body.scrollTop=body.scrollHeight;}
function open(projectId){activeProjectId=projectId;const root=modal();render();root.classList.remove('hidden');document.body.style.overflow='hidden';setTimeout(()=>root.querySelector('[data-copilot-input]')?.focus(),50);}
function close(){controller?.abort();const root=document.getElementById('atlas-copilot-modal');root?.classList.add('hidden');document.body.style.overflow='';running=false;}
async function send(){if(running||!activeProjectId)return;const root=modal(),input=root.querySelector('[data-copilot-input]'),message=input.value.trim();if(!message)return;const project=readProjects().find(item=>item.id===activeProjectId);if(!project)return;const items=history(activeProjectId);items.push({role:'user',content:message});input.value='';running=true;root.querySelector('[data-copilot-send]').disabled=true;render();controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),52000);try{const response=await fetch('/api/copilot',{method:'POST',headers:{'content-type':'application/json'},signal:controller.signal,body:JSON.stringify({message,locale:getLocale(),project:compactProject(project),history:items.slice(-8)})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||copy().failed);items.push({role:'assistant',content:data.answer||copy().failed,actions:Array.isArray(data.actions)?data.actions:[]});}catch(error){items.push({role:'assistant',content:error?.name==='AbortError'?(getLocale()==='en'?'The Copilot took too long. Try a shorter question.':'El Copiloto tardó demasiado. Prueba con una pregunta más breve.'):(error.message||copy().failed),actions:[]});}finally{clearTimeout(timeout);controller=null;running=false;root.querySelector('[data-copilot-send]').disabled=false;render();}}
function enhanceWorkspace(){document.querySelectorAll('.workspace-card[data-project-id]').forEach(card=>{const actions=card.querySelector('.workspace-actions');if(!actions||actions.querySelector('[data-atlas-copilot]'))return;const button=document.createElement('button');button.type='button';button.dataset.atlasCopilot='';button.textContent=copy().button;button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();open(card.dataset.projectId);});actions.appendChild(button);});}
function schedule(){requestAnimationFrame(enhanceWorkspace);setTimeout(enhanceWorkspace,100);}
document.addEventListener('click',event=>{if(event.target.closest('.workspace-open,.workspace-back,[data-action]'))schedule();});window.addEventListener('atlas:locale',()=>{schedule();if(!document.getElementById('atlas-copilot-modal')?.classList.contains('hidden'))render();});window.addEventListener('pagehide',()=>controller?.abort());schedule();
