import { getLocale } from './i18n.js';
import { track } from './tracking.js';

const KEY='atlas-free-analysis-completed-at';
const DAY=86400000;
const $=id=>document.getElementById(id);
let initialized=false;

function text(){return getLocale()==='en'?{plan:'Atlas Free',available:'1 full analysis available',used:'Full analysis used',limitTitle:'Your next free analysis is not available yet',limitBody:h=>`You can analyze another idea in ${h}. Your current report remains available.`,pro:'Join Atlas Pro waitlist',title:'Turn this idea into a project',body:'Save the analysis, return with new evidence, compare progress and continue the validation plan with Atlas Pro.',features:['Saved projects','Progress history','Evidence reanalysis','Idea comparison'],email:'Your email',submit:'Join Atlas Pro',continue:'Continue with Free',success:'You are on the Atlas Pro waitlist.',error:'We could not save your request. Please try again.'}:{plan:'Atlas Free',available:'1 análisis completo disponible',used:'Análisis completo utilizado',limitTitle:'Tu siguiente análisis gratuito aún no está disponible',limitBody:h=>`Podrás analizar otra idea dentro de ${h}. Tu informe actual sigue disponible.`,pro:'Apuntarme a Atlas Pro',title:'Convierte esta idea en un proyecto',body:'Guarda el análisis, vuelve con nueva evidencia, compara la evolución y continúa el plan de validación con Atlas Pro.',features:['Proyectos guardados','Historial de evolución','Reanálisis de evidencia','Comparador de ideas'],email:'Tu correo',submit:'Apuntarme a Atlas Pro',continue:'Seguir con Free',success:'Ya estás en la lista de Atlas Pro.',error:'No pudimos guardar tu solicitud. Inténtalo de nuevo.'};}
function remaining(){const at=Number(localStorage.getItem(KEY)||0);return Math.max(0,DAY-(Date.now()-at));}
function duration(ms){const h=Math.ceil(ms/3600000);return getLocale()==='en'?`${h} hour${h===1?'':'s'}`:`${h} hora${h===1?'':'s'}`;}
export function isFreeLimited(){return remaining()>0;}

function style(){if($('atlas-free-style'))return;const s=document.createElement('style');s.id='atlas-free-style';s.textContent='.free-plan-status{display:flex;justify-content:space-between;gap:12px;margin:-4px 0 22px;padding:13px 15px;border:1px solid rgba(91,201,255,.22);border-radius:15px;background:rgba(91,201,255,.055)}.free-plan-status div{display:grid;gap:3px}.free-plan-status span{color:var(--muted);font-size:12px}.free-plan-status>b{color:var(--blue);font-size:12px;letter-spacing:.1em}.free-limit-card,.pro-upsell{margin-top:18px;padding:18px;border:1px solid rgba(122,140,255,.32);border-radius:17px;background:linear-gradient(145deg,rgba(18,31,54,.98),rgba(9,20,36,.98))}.free-limit-card p,.pro-upsell>p{color:var(--muted);line-height:1.55}.pro-upsell h4{font-size:25px;margin:4px 0 8px}.pro-feature-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:14px 0}.pro-feature-grid span{border:1px solid var(--line);border-radius:12px;background:#081523;padding:12px}.pro-feature-grid span:before{content:"✦";color:var(--blue);margin-right:8px}.pro-waitlist-form{display:grid;grid-template-columns:1fr auto;gap:8px}.pro-waitlist-form input{min-width:0;border:1px solid var(--line);border-radius:14px;background:#071321;color:var(--text);padding:14px;font:inherit}@media(max-width:580px){.pro-feature-grid,.pro-waitlist-form{grid-template-columns:1fr}}@media print{.free-plan-status,.free-limit-card,.pro-upsell{display:none!important}}';document.head.appendChild(s);}
function refresh(){if(!initialized)return;const c=text();$('free-plan-name').textContent=c.plan;$('free-plan-copy').textContent=isFreeLimited()?c.used:c.available;$('free-limit-title').textContent=c.limitTitle;$('free-limit-copy').textContent=c.limitBody(duration(remaining()));$('free-limit-pro').textContent=c.pro;$('pro-title').textContent=c.title;$('pro-copy').textContent=c.body;document.querySelectorAll('[data-free-feature]').forEach((el,i)=>el.textContent=c.features[i]);$('pro-email').placeholder=c.email;$('pro-submit').textContent=c.submit;$('continue-free').textContent=c.continue;}
async function waitlist(e){e.preventDefault();const c=text();const email=$('pro-email').value.trim();$('pro-submit').disabled=true;try{const r=await fetch('/api/waitlist',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,language:getLocale(),source:'report_free_upsell'})});if(!r.ok)throw new Error();$('pro-message').textContent=c.success;track('pro_waitlist_from_report');e.target.reset();}catch{$('pro-message').textContent=c.error;}finally{$('pro-submit').disabled=false;}}
export function initFreePlan(){if(initialized)return;style();const app=document.querySelector('.app-card');const progress=document.querySelector('.progress-row');const start=$('start-view');const report=$('report-view');if(!app||!progress||!start||!report)return;const status=document.createElement('div');status.className='free-plan-status';status.innerHTML='<div><strong id="free-plan-name"></strong><span id="free-plan-copy"></span></div><b>FREE</b>';app.insertBefore(status,progress);const limit=document.createElement('section');limit.id='free-limit-card';limit.className='free-limit-card hidden';limit.innerHTML='<strong id="free-limit-title"></strong><p id="free-limit-copy"></p><button id="free-limit-pro" class="secondary-button" type="button"></button>';start.appendChild(limit);const pro=document.createElement('section');pro.id='pro-upsell';pro.className='pro-upsell hidden';pro.innerHTML='<p class="eyebrow">ATLAS PRO</p><h4 id="pro-title"></h4><p id="pro-copy"></p><div class="pro-feature-grid"><span data-free-feature></span><span data-free-feature></span><span data-free-feature></span><span data-free-feature></span></div><form id="pro-form" class="pro-waitlist-form"><input id="pro-email" type="email" autocomplete="email" required><button id="pro-submit" class="button" type="submit"></button></form><p id="pro-message" class="helper"></p><button id="continue-free" class="text-button" type="button"></button>';report.insertBefore(pro,report.querySelector('.report-actions'));$('pro-form').addEventListener('submit',waitlist);$('continue-free').addEventListener('click',()=>{pro.classList.add('hidden');track('continue_free_clicked');});$('free-limit-pro').addEventListener('click',()=>{track('pro_upsell_viewed',{source:'free_limit'});});window.addEventListener('atlas:locale',refresh);initialized=true;refresh();if(!isFreeLimited())track('free_analysis_available');}
export function guardFreeStart(){if(!isFreeLimited())return true;refresh();$('free-limit-card')?.classList.remove('hidden');track('free_limit_reached');return false;}
export function completeFreeAnalysis(){if(!isFreeLimited()){localStorage.setItem(KEY,String(Date.now()));track('free_analysis_consumed');}$('pro-upsell')?.classList.remove('hidden');track('pro_upsell_viewed',{source:'report'});refresh();}
export function resetFreeView(){$('free-limit-card')?.classList.toggle('hidden',!isFreeLimited());refresh();}
