const STORAGE_KEY = 'atlas-locale';

const translations = {
  es: {
    meta: { title: 'Atlas — Pon a prueba tu idea antes de construirla', description: 'Separa hechos de supuestos, detecta riesgos y recibe una prueba medible antes de invertir meses en una idea de negocio.' },
    nav: { how: 'Cómo funciona', example: 'Qué recibes', principles: 'Principios', try: 'Probar Atlas' },
    hero: { eyebrow: 'Atlas Validator · Beta privada', title: 'Pon a prueba tu idea', titleAccent: 'antes de construirla.', copy: 'Atlas te ayuda a separar lo que sabes de lo que supones, detectar los riesgos que pueden invalidar la oportunidad y diseñar una prueba concreta antes de invertir meses de trabajo.', cta: 'Analizar mi idea', secondary: 'Ver qué recibiré', note: 'Sin registro · Aproximadamente 3 minutos · Informe accionable' },
    proof: { report: 'Informe Atlas', verdictLabel: 'VEREDICTO', verdict: 'Validar antes de construir', summary: 'La oportunidad es plausible, pero la adquisición de clientes y la disposición a pagar siguen siendo supuestos.', strengths: 'señales', risks: 'riesgos', experiment: 'prueba' },
    trust: ['No predice el éxito.', 'No inventa evidencia.', 'Te dice qué debes demostrar.'],
    process: { eyebrow: 'Cómo funciona', title: 'De una intuición a una decisión.', copy: 'Atlas construye el análisis a partir de tu idea y de la evidencia que aportas.', steps: [ ['Describe la oportunidad', 'Explica qué quieres construir, para quién, qué problema resuelve y cómo generaría valor.'], ['Expón tus supuestos', 'Atlas formula preguntas adaptadas para localizar contradicciones, vacíos y afirmaciones sin demostrar.'], ['Decide el siguiente paso', 'Recibe un informe y una prueba medible para continuar, reformular o detenerte antes de construir.'] ] },
    principles: { eyebrow: 'Principios Atlas', title: 'Menos convicción.\nMás evidencia.', lines: ['Atlas no adivina el futuro.', 'No convierte una intuición en una certeza.', 'Distingue hechos, supuestos y señales que todavía faltan.'], strong: 'La pregunta útil no es «¿me gusta esta idea?». Es «¿qué tendría que ser cierto para que merezca la pena construirla?».' },
    example: { eyebrow: 'Qué recibes', title: 'Un informe diseñado para tomar una decisión.', copy: 'No es una predicción. Es un mapa de lo que parece favorable, lo que sigue abierto y la prueba que reduce más incertidumbre.', idea: 'Idea analizada', name: 'Marketplace de veterinarios a domicilio', status: 'VALIDAR ANTES DE CONSTRUIR', summary: 'Existe una necesidad reconocible, pero el modelo depende de conseguir oferta local suficiente y clientes con urgencia y disposición a pagar.', cards: [['Señal favorable','Problema claro y de alta fricción para el cliente.'],['Riesgo abierto','Adquisición local y disponibilidad inmediata de profesionales.'],['Supuesto crítico','Los propietarios pagarán una prima por evitar desplazamientos.'],['Próxima prueba','Captar diez solicitudes reales en un barrio antes de desarrollar la plataforma.']] },
    validator: { eyebrow: 'Atlas Validator', title: 'Convierte una idea en una decisión.', copy: 'Describe la oportunidad con claridad. Atlas te hará preguntas para separar hechos de suposiciones y terminará con una prueba concreta.', bullets: ['Preguntas adaptadas a tu idea','Riesgos y supuestos sin demostrar','Informe y experimento de validación'], label: '¿Qué oportunidad quieres poner a prueba?', helper: 'Incluye qué harías, para quién, qué problema resolverías y cómo ganarías dinero.', placeholder: 'Ejemplo: una newsletter de pago para profesionales que quieren conseguir clientes con LinkedIn', analyze: 'Analizar idea', answerPlaceholder: 'Responde con hechos, cifras o ejemplos concretos cuando puedas', continue: 'Continuar', restart: 'Reiniciar análisis', loadingTitle: 'Atlas está evaluando la evidencia', verdict: 'Veredicto', strengths: 'Señales favorables', risks: 'Riesgos', assumptions: 'Supuestos críticos', dont: 'No construyas todavía', share: 'Compartir', pdf: 'Descargar PDF', another: 'Analizar otra idea' },
    cta: { eyebrow: 'Antes de construir', title: 'Dedica cinco minutos a descubrir la prueba que puede ahorrarte meses.', button: 'Poner a prueba mi idea' },
    footer: { tagline: 'Ayudamos a pensar mejor antes de construir.', product: 'Producto', principles: 'Principios', manifesto: 'Manifiesto', private: 'Beta privada', noPublish: 'No publicar antes de 3.4', disclaimer: 'El análisis es orientativo y no sustituye investigación de mercado.' },
    runtime: { fallbackQuestion: 'Cuéntanos un poco más', adapted: 'Pregunta adaptada', question: 'Pregunta {current} de {total}', stopped: 'Análisis detenido', blockedVerdict: 'IDEA NO EVALUABLE', blockedSummary: 'Atlas no analiza ni proporciona planes para actividades ilegales o dañinas.', blockedRisk: 'La actividad descrita no puede recibir asistencia comercial.', blockedDont: 'No continúes con esta idea. Reformúlala hacia una actividad legal y segura.', safeStep: 'Siguiente paso seguro', safeAction: 'Describe una alternativa legal que resuelva un problema real sin causar daño.', detailError: 'Describe la idea con un poco más de detalle.', analyzing: 'Analizando idea', stepOne: 'Paso 1 de 1', preparing: 'Preparando informe', reportError: 'No se pudo generar el informe', retry: 'Reintentar', copied: 'Copiado', validationReport: 'Informe de validación', score: 'Puntuación', reportReady: 'Informe preparado', completed: 'Análisis completado', defaultVerdict: 'VALIDAR ANTES DE CONSTRUIR', defaultSummary: 'Atlas ha identificado qué deberías demostrar antes de invertir más tiempo.', experiment: 'Experimento de 7 días', insufficientEvidence: 'Sin datos suficientes.', languageMismatch: 'Este bloque no estaba disponible de forma fiable en el idioma seleccionado.', loading: ['Interpretando la oportunidad…','Separando hechos de supuestos…','Identificando riesgos abiertos…','Preparando la prueba más útil…'] }
  },
  en: {
    meta: { title: 'Atlas — Test your idea before you build it', description: 'Separate facts from assumptions, identify risks and get a measurable test before investing months in a business idea.' },
    nav: { how: 'How it works', example: 'What you get', principles: 'Principles', try: 'Try Atlas' },
    hero: { eyebrow: 'Atlas Validator · Private beta', title: 'Test your idea', titleAccent: 'before you build it.', copy: 'Atlas helps you separate what you know from what you assume, identify the risks that could invalidate the opportunity, and design a concrete test before investing months of work.', cta: 'Analyze my idea', secondary: 'See what you get', note: 'No sign-up · About 3 minutes · Actionable report' },
    proof: { report: 'Atlas report', verdictLabel: 'VERDICT', verdict: 'Validate before building', summary: 'The opportunity is plausible, but customer acquisition and willingness to pay remain assumptions.', strengths: 'signals', risks: 'risks', experiment: 'test' },
    trust: ['It does not predict success.', 'It does not invent evidence.', 'It tells you what to prove.'],
    process: { eyebrow: 'How it works', title: 'From intuition to decision.', copy: 'Atlas builds the analysis around your idea and the evidence you provide.', steps: [ ['Describe the opportunity', 'Explain what you want to build, who it is for, what problem it solves and how it creates value.'], ['Expose your assumptions', 'Atlas asks tailored questions to find contradictions, gaps and claims that remain unproven.'], ['Choose the next step', 'Get a report and a measurable test to continue, reshape or stop before you build.'] ] },
    principles: { eyebrow: 'Atlas principles', title: 'Less conviction.\nMore evidence.', lines: ['Atlas does not predict the future.', 'It does not turn intuition into certainty.', 'It separates facts, assumptions and missing signals.'], strong: 'The useful question is not “do I like this idea?”. It is “what would need to be true for this to be worth building?”.' },
    example: { eyebrow: 'What you get', title: 'A report designed to support a decision.', copy: 'It is not a prediction. It is a map of what looks promising, what remains open and which test reduces the most uncertainty.', idea: 'Idea analyzed', name: 'Marketplace for at-home veterinarians', status: 'VALIDATE BEFORE BUILDING', summary: 'There is a recognizable need, but the model depends on enough local supply and customers with urgency and willingness to pay.', cards: [['Positive signal','A clear, high-friction problem for the customer.'],['Open risk','Local acquisition and immediate professional availability.'],['Critical assumption','Owners will pay a premium to avoid travel.'],['Next test','Capture ten real requests in one neighborhood before building the platform.']] },
    validator: { eyebrow: 'Atlas Validator', title: 'Turn an idea into a decision.', copy: 'Describe the opportunity clearly. Atlas will ask questions to separate facts from assumptions and finish with a concrete test.', bullets: ['Questions tailored to your idea','Risks and unproven assumptions','Report and validation experiment'], label: 'What opportunity do you want to test?', helper: 'Include what you would do, for whom, what problem you solve and how you make money.', placeholder: 'Example: a paid newsletter for professionals who want to win clients through LinkedIn', analyze: 'Analyze idea', answerPlaceholder: 'Use facts, numbers or concrete examples whenever possible', continue: 'Continue', restart: 'Restart analysis', loadingTitle: 'Atlas is evaluating the evidence', verdict: 'Verdict', strengths: 'Positive signals', risks: 'Risks', assumptions: 'Critical assumptions', dont: 'Do not build yet', share: 'Share', pdf: 'Download PDF', another: 'Analyze another idea' },
    cta: { eyebrow: 'Before you build', title: 'Spend five minutes finding the test that could save you months.', button: 'Test my idea' },
    footer: { tagline: 'Helping people think better before they build.', product: 'Product', principles: 'Principles', manifesto: 'Manifesto', private: 'Private beta', noPublish: 'Do not launch before 3.4', disclaimer: 'The analysis is directional and does not replace market research.' },
    runtime: { fallbackQuestion: 'Tell us a little more', adapted: 'Tailored question', question: 'Question {current} of {total}', stopped: 'Analysis stopped', blockedVerdict: 'IDEA NOT ELIGIBLE', blockedSummary: 'Atlas does not analyze or provide plans for illegal or harmful activities.', blockedRisk: 'The described activity cannot receive business assistance.', blockedDont: 'Do not continue with this idea. Reframe it as a legal and safe activity.', safeStep: 'Safe next step', safeAction: 'Describe a legal alternative that solves a real problem without causing harm.', detailError: 'Describe the idea in a little more detail.', analyzing: 'Analyzing idea', stepOne: 'Step 1 of 1', preparing: 'Preparing report', reportError: 'The report could not be generated', retry: 'Try again', copied: 'Copied', validationReport: 'Validation report', score: 'Score', reportReady: 'Report ready', completed: 'Analysis complete', defaultVerdict: 'VALIDATE BEFORE BUILDING', defaultSummary: 'Atlas has identified what you should prove before investing more time.', experiment: '7-day experiment', insufficientEvidence: 'Insufficient evidence.', languageMismatch: 'This block was not reliably available in the selected language.', loading: ['Interpreting the opportunity…','Separating facts from assumptions…','Identifying open risks…','Preparing the most useful test…'] }
  }
};

let locale = localStorage.getItem(STORAGE_KEY) || (navigator.language?.toLowerCase().startsWith('es') ? 'es' : 'en');
if (!translations[locale]) locale = 'en';

function getPath(source, path) { return path.split('.').reduce((value, key) => value?.[key], source); }
export function t(path, vars = {}) { let value = getPath(translations[locale], path) ?? path; if (typeof value !== 'string') return value; return value.replace(/\{(\w+)\}/g, (_, key) => vars[key] ?? ''); }
export function getLocale() { return locale; }
export function setLocale(next) { if (!translations[next]) return; locale = next; localStorage.setItem(STORAGE_KEY, next); applyTranslations(); window.dispatchEvent(new CustomEvent('atlas:locale', { detail: { locale } })); }
export function applyTranslations() {
  document.documentElement.lang = locale;
  document.title = t('meta.title');
  document.querySelector('meta[name="description"]')?.setAttribute('content', t('meta.description'));
  document.querySelectorAll('[data-i18n]').forEach((el) => { const value = t(el.dataset.i18n); el.textContent = value; });
  document.querySelectorAll('[data-i18n-html]').forEach((el) => { el.innerHTML = t(el.dataset.i18nHtml).replace(/\n/g, '<br>'); });
  document.querySelectorAll('[data-i18n-placeholder]').forEach((el) => el.setAttribute('placeholder', t(el.dataset.i18nPlaceholder)));
  document.querySelectorAll('[data-locale]').forEach((el) => el.setAttribute('aria-pressed', String(el.dataset.locale === locale)));
  document.querySelectorAll('.language-switcher').forEach((el) => el.dataset.activeLocale = locale);
}
export function initI18n() {
  document.querySelectorAll('[data-locale]').forEach((button) => button.addEventListener('click', () => setLocale(button.dataset.locale)));
  applyTranslations();
}