import { byId, escapeHtml, safeText } from './dom.js';
import { getLocale, t } from './i18n.js';
import { renderEngagement } from './engagement.js';
import { renderList, setProgress, showView } from './ui.js';

const VERDICT_MAP={es:{discard:'DESCARTAR',rejected:'DESCARTAR',reject:'DESCARTAR','do not build':'NO CONSTRUIR TODAVÍA',reformulate:'REFORMULAR Y PROBAR',reshape:'REFORMULAR Y PROBAR',validate:'VALIDAR ANTES DE CONSTRUIR','validate before building':'VALIDAR ANTES DE CONSTRUIR','idea not eligible':'IDEA NO EVALUABLE'},en:{descartar:'DISCARD',rechazada:'DISCARD',rechazado:'DISCARD','no construir todavía':'DO NOT BUILD YET',reformular:'REFRAME AND TEST','reformular y probar':'REFRAME AND TEST',validar:'VALIDATE BEFORE BUILDING','validar antes de construir':'VALIDATE BEFORE BUILDING','idea no evaluable':'IDEA NOT ELIGIBLE'}};
const PHRASE_MAP={es:{'insufficient evidence.':'Sin datos suficientes.','insufficient evidence':'Sin datos suficientes.','not enough data.':'Sin datos suficientes.','not enough data':'Sin datos suficientes.'},en:{'sin datos suficientes.':'Insufficient evidence.','sin datos suficientes':'Insufficient evidence.','no hay datos suficientes.':'Insufficient evidence.','no hay datos suficientes':'Insufficient evidence.','información insuficiente.':'Insufficient evidence.','información insuficiente':'Insufficient evidence.'}};
const SPANISH_MARKERS=/\b(el|la|los|las|una|un|para|con|sin|datos|suficientes|riesgo|supuesto|cliente|negocio|mercado|pagar|construir|todavía|prueba|evidencia)\b/gi;
const ENGLISH_MARKERS=/\b(the|a|an|for|with|without|data|evidence|risk|assumption|customer|business|market|pay|build|test|still|insufficient)\b/gi;
function markerCount(text,pattern){return(String(text).toLowerCase().match(pattern)||[]).length;}
function isWrongLanguage(text){const value=safeText(text);if(!value||value.length<12)return false;const spanish=markerCount(value,SPANISH_MARKERS),english=markerCount(value,ENGLISH_MARKERS);return getLocale()==='en'?spanish>=2&&spanish>english:english>=2&&english>spanish;}
function normalizeText(value,fallback='runtime.languageMismatch'){const text=safeText(value);if(!text)return'';const mapped=PHRASE_MAP[getLocale()]?.[text.toLowerCase().trim()];if(mapped)return mapped;return isWrongLanguage(text)?t(fallback):text;}
function normalizeList(values,{fallback=true}={}){if(!Array.isArray(values)||!values.length)return fallback?[t('runtime.insufficientEvidence')]:[];const normalized=values.map(item=>normalizeText(item)).filter(Boolean);return normalized.length?normalized:(fallback?[t('runtime.insufficientEvidence')]:[]);}
function normalizeVerdict(value){const text=safeText(value);if(!text)return t('runtime.defaultVerdict');const key=text.toLowerCase().trim();return VERDICT_MAP[getLocale()]?.[key]||normalizeText(text,'runtime.defaultVerdict');}
export function normalizeReport(report={}){const experiment=report.experiment||report.validationExperiment||{};return{...report,verdict:normalizeVerdict(report.verdict),executiveSummary:normalizeText(report.executiveSummary||report.summary,'runtime.defaultSummary')||t('runtime.defaultSummary'),strengths:normalizeList(report.strengths),risks:normalizeList(report.risks),criticalAssumptions:normalizeList(report.criticalAssumptions||report.assumptions),contradictions:normalizeList(report.contradictions,{fallback:false}),recommendations:normalizeList(report.recommendations,{fallback:false}),doNotBuildYet:normalizeList(report.doNotBuildYet),scoreBreakdown:report.scoreBreakdown||{},experiment:{...experiment,name:normalizeText(experiment.name)||t('runtime.experiment'),hypothesis:normalizeText(experiment.hypothesis),target:normalizeText(experiment.target),metric:normalizeText(experiment.metric),successThreshold:normalizeText(experiment.successThreshold),failureThreshold:normalizeText(experiment.failureThreshold),decisionIfSuccess:normalizeText(experiment.decisionIfSuccess),decisionIfFailure:normalizeText(experiment.decisionIfFailure),steps:normalizeList(experiment.steps)}};}
function labels(){return getLocale()==='en'?{complete:'Complete',contradictions:'Contradictions detected',recommendations:'Recommended next actions',score:'Evidence score',problem:'Problem evidence',customer:'Customer specificity',payment:'Payment evidence',distribution:'Distribution feasibility',economics:'Delivery economics',hypothesis:'Hypothesis',target:'Target',metric:'Metric',success:'Success threshold',failure:'Failure threshold',yes:'If successful',no:'If unsuccessful'}:{complete:'Completar',contradictions:'Contradicciones detectadas',recommendations:'Próximas acciones recomendadas',score:'Puntuación de evidencia',problem:'Evidencia del problema',customer:'Especificidad del cliente',payment:'Evidencia de pago',distribution:'Viabilidad de distribución',economics:'Economía de entrega',hypothesis:'Hipótesis',target:'Objetivo',metric:'Métrica',success:'Umbral de éxito',failure:'Umbral de fracaso',yes:'Si funciona',no:'Si no funciona'};}
function ensureAdvancedStyles(){if(document.getElementById('atlas-33-report-styles'))return;const style=document.createElement('style');style.id='atlas-33-report-styles';style.textContent=`.atlas-33-insights{display:grid;gap:16px;margin:18px 0}.atlas-33-card{padding:20px;border:1px solid rgba(132,180,240,.2);border-radius:18px;background:rgba(5,16,30,.5)}.atlas-33-card h4{margin:0 0 12px}.score-breakdown{display:grid;gap:10px}.score-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center}.score-row span{color:var(--muted)}.score-row strong{font-size:14px}.experiment-meta{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0 18px}.experiment-meta div{padding:12px;border-radius:12px;background:rgba(255,255,255,.035)}.experiment-meta strong{display:block;font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:var(--accent);margin-bottom:4px}.experiment-meta span{color:var(--muted);line-height:1.45}.experiment-task label{display:flex;gap:10px;align-items:flex-start}.experiment-task.is-complete span{text-decoration:line-through;opacity:.58}@media(max-width:720px){.experiment-meta{grid-template-columns:1fr}}`;document.head.appendChild(style);}
function renderAdvancedInsights(report){ensureAdvancedStyles();document.getElementById('atlas-33-insights')?.remove();const grid=byId('strengths')?.closest('.report-grid');if(!grid)return;const l=labels();const breakdown=report.scoreBreakdown||{};const scoreRows=[['problemEvidence',l.problem],['customerSpecificity',l.customer],['paymentEvidence',l.payment],['distributionFeasibility',l.distribution],['deliveryEconomics',l.economics]].map(([key,label])=>`<div class="score-row"><span>${escapeHtml(label)}</span><strong>${Number(breakdown[key]||0)}/20</strong></div>`).join('');const contradictions=report.contradictions?.length?`<article class="atlas-33-card"><h4>${l.contradictions}</h4><ul>${report.contradictions.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul></article>`:'';const recommendations=report.recommendations?.length?`<article class="atlas-33-card"><h4>${l.recommendations}</h4><ul>${report.recommendations.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul></article>`:'';grid.insertAdjacentHTML('afterend',`<section id="atlas-33-insights" class="atlas-33-insights"><article class="atlas-33-card"><h4>${l.score}</h4><div class="score-breakdown">${scoreRows}</div></article>${contradictions}${recommendations}</section>`);}
function renderExperimentMeta(experiment){document.getElementById('experiment-meta')?.remove();const list=byId('experiment-steps');if(!list)return;const l=labels();const fields=[[l.hypothesis,experiment.hypothesis],[l.target,experiment.target],[l.metric,experiment.metric],[l.success,experiment.successThreshold],[l.failure,experiment.failureThreshold],[l.yes,experiment.decisionIfSuccess],[l.no,experiment.decisionIfFailure]].filter(([,value])=>value);if(!fields.length)return;list.insertAdjacentHTML('beforebegin',`<div id="experiment-meta" class="experiment-meta">${fields.map(([label,value])=>`<div><strong>${escapeHtml(label)}</strong><span>${escapeHtml(value)}</span></div>`).join('')}</div>`);}
function renderInteractiveExperiment(steps){const list=byId('experiment-steps');const label=labels().complete;list.innerHTML=steps.map((step,index)=>`<li class="experiment-task"><label><input type="checkbox" data-experiment-step="${index}"><span>${escapeHtml(String(step))}</span></label></li>`).join('');const progress=document.createElement('p');progress.id='experiment-progress';progress.className='helper';list.insertAdjacentElement('afterend',progress);const update=()=>{const boxes=[...document.querySelectorAll('[data-experiment-step]')];const completed=boxes.filter(box=>box.checked).length;progress.textContent=`${completed}/${boxes.length} ${label}`;boxes.forEach(box=>box.closest('li')?.classList.toggle('is-complete',box.checked));};document.querySelectorAll('[data-experiment-step]').forEach(box=>box.addEventListener('change',update));update();}
export function renderReport(report={}){const normalized=normalizeReport(report);byId('score').textContent=Number.isFinite(Number(normalized.score))?Math.round(Number(normalized.score)):'—';byId('verdict').textContent=normalized.verdict;byId('summary').textContent=normalized.executiveSummary;renderList('strengths',normalized.strengths);renderList('risks',normalized.risks);renderList('assumptions',normalized.criticalAssumptions);renderList('do-not-build',normalized.doNotBuildYet);renderAdvancedInsights(normalized);byId('experiment-name').textContent=normalized.experiment.name;document.getElementById('experiment-progress')?.remove();renderExperimentMeta(normalized.experiment);renderInteractiveExperiment(normalized.experiment.steps);renderEngagement();}
export async function revealReport(report){setProgress(96,t('runtime.reportReady'));await new Promise(resolve=>setTimeout(resolve,650));renderReport(report);showView('report-view');setProgress(100,t('runtime.completed'));}
