import crypto from 'node:crypto';
const STRIPE='https://api.stripe.com/v1',SUPABASE='https://ntrnchrtnfjyrsagxxbo.supabase.co',ORIGIN='https://atlas-beta-2.vercel.app';
const PRICES={monthly:'price_1U2825ENQtHnWsv9hHUAuODi',annual:'price_1U283aENQtHnWsv9mUQrXGy8'},INTERVAL=Object.fromEntries(Object.entries(PRICES).map(([k,v])=>[v,k]));
export const config={api:{bodyParser:false}};
const enabled=()=>process.env.ATLAS_BILLING_ENABLED==='true';
async function raw(req){const chunks=[];for await(const c of req)chunks.push(Buffer.from(c));return Buffer.concat(chunks);}
function bearer(req){const v=String(req.headers.authorization||'');return v.toLowerCase().startsWith('bearer ')?v.slice(7):'';}
async function user(token){const key=process.env.SUPABASE_ANON_KEY;if(!key||!token)return null;const r=await fetch(`${SUPABASE}/auth/v1/user`,{headers:{authorization:`Bearer ${token}`,apikey:key}});return r.ok?r.json():null;}
async function stripe(path,body){const secret=process.env.STRIPE_SECRET_KEY;if(!secret)throw new Error('stripe_not_configured');const r=await fetch(`${STRIPE}${path}`,{method:'POST',headers:{authorization:`Bearer ${secret}`,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(body)}),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'stripe_failed');return d;}
async function plan(userId){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw new Error('supabase_service_not_configured');const r=await fetch(`${SUPABASE}/rest/v1/atlas_user_plans?user_id=eq.${encodeURIComponent(userId)}&select=*&limit=1`,{headers:{authorization:`Bearer ${key}`,apikey:key}}),rows=await r.json();return r.ok?rows?.[0]:null;}
async function patch(userId,data){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw new Error('supabase_service_not_configured');const r=await fetch(`${SUPABASE}/rest/v1/atlas_user_plans?user_id=eq.${encodeURIComponent(userId)}`,{method:'PATCH',headers:{authorization:`Bearer ${key}`,apikey:key,'content-type':'application/json',prefer:'return=minimal'},body:JSON.stringify({...data,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error('plan_update_failed');}
function verify(payload,header){const secret=process.env.STRIPE_WEBHOOK_SECRET;if(!secret||!header)return false;const parts=Object.fromEntries(header.split(',').map(x=>x.split('='))),signed=`${parts.t}.${payload.toString('utf8')}`,expected=crypto.createHmac('sha256',secret).update(signed).digest('hex'),given=parts.v1||'';return expected.length===given.length&&crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(given));}
async function webhook(req,res,payload){if(!verify(payload,String(req.headers['stripe-signature']||'')))return res.status(400).json({error:'invalid_signature'});const event=JSON.parse(payload.toString('utf8')),o=event.data?.object||{};if(event.type.startsWith('customer.subscription.')&&o.metadata?.atlas_user_id){const price=o.items?.data?.[0]?.price?.id||null,pro=['active','trialing'].includes(o.status);await patch(o.metadata.atlas_user_id,{plan:pro?'pro':'free',status:pro?'active':o.status||'inactive',source:'stripe',stripe_customer_id:o.customer||null,stripe_subscription_id:o.id||null,stripe_price_id:price,billing_interval:INTERVAL[price]||null,current_period_end:o.current_period_end?new Date(o.current_period_end*1000).toISOString():null,cancel_at_period_end:Boolean(o.cancel_at_period_end)});}return res.status(200).json({received:true});}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});if(!enabled())return res.status(503).json({error:'billing_disabled'});const payload=await raw(req);try{if(req.headers['stripe-signature'])return webhook(req,res,payload);const body=payload.length?JSON.parse(payload.toString('utf8')):{},u=await user(bearer(req));if(!u?.id)return res.status(401).json({error:'auth_required'});if(body.action==='portal'){const row=await plan(u.id);if(!row?.stripe_customer_id)return res.status(404).json({error:'billing_customer_not_found'});const s=await stripe('/billing_portal/sessions',{customer:row.stripe_customer_id,return_url:`${ORIGIN}/#atlas-pro`});return res.status(200).json({url:s.url});}const billing=body.billing==='monthly'?'monthly':'annual',s=await stripe('/checkout/sessions',{mode:'subscription','line_items[0][price]':PRICES[billing],'line_items[0][quantity]':'1',customer_email:u.email,client_reference_id:u.id,'subscription_data[metadata][atlas_user_id]':u.id,'metadata[atlas_user_id]':u.id,'metadata[atlas_billing]':billing,success_url:`${ORIGIN}/?billing=success#atlas-pro`,cancel_url:`${ORIGIN}/#atlas-pro`,'allow_promotion_codes':'true'});return res.status(200).json({url:s.url});}catch(e){console.error('billing_failed',e);return res.status(500).json({error:'billing_failed'});}}